language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
# removed 3.3 because scipy gives and error
sudo: required
install:
    - sudo apt-get install liblapack-dev libblas-dev gfortran
    - pip install -v .
    - pip install -r requirements.txt
    - pip install coveralls
script:
    - py.test
    - coverage run --source=allantools setup.py test
after_success:
    coveralls
